Lab_Investigacion/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404
from .views import index
from .views import login
from .views import pag404

handler404 = 'Lab_Investigacion.views.pag404'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name = 'index'),
    path('Lab/',include(('proyecto.urls','proyecto'))),#accounts/login/
    path('accounts/login/',login,name='login'),
]

#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyecto/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import inicio
from .views import ejemplo
from .views import crear_proyecto
from .views import crear_cuenta
from .views import nuevo_pdf
from .views import nuevo_miembro
from .views import lista_proyectos
from .views import editar_proyecto
from .views import Sesion
from .views import salirUsuario
from .views import crear_usuario_oficial
from .views import pag_proyecto
from .views import borrar_integrante
from .views import lista_sintesis
from .views import editar_usuario
from .views import comentarios
from .views import lista_registros
from .views import subir_lan
from .views import act_lan
from .views import dec_lan
from .views import pag404
from .views import subir_documento
from .views import act_documento
from .views import des_documento
from .views import elim_documento
from .views import borrar_comentario
from .views import borrar_pdf
#from .views import
#from .views import sesion

urlpatterns = [
    path('',inicio, name = 'inicio'),
    path('crear_proyecto/', login_required(crear_proyecto), name='crear_proyecto'),
    path('nuevo_usuario/', login_required(crear_cuenta), name='crear_cuenta'),
    path('subir_pdf/<id>', login_required(nuevo_pdf), name='nuevo_pdf'),
    path('integrantes/<id>', login_required(nuevo_miembro), name='nuevo_miembro'),
    path('lista_proyectos/', login_required(lista_proyectos), name='lista_proyectos'),
    path('editar_proyecto/<id>', login_required(editar_proyecto), name="editar_proyecto"),
    path('sesion/', Sesion.as_view(), name='sesion'),
    path('salir/', login_required(salirUsuario), name='salir'),
    path('crear_usuario/', login_required(crear_usuario_oficial), name='crear_usuario'),
    path('proyecto/<id>', login_required(pag_proyecto), name='pag_proyecto'),
    path('borrar_int/<id>/<us>', login_required(borrar_integrante), name='borrar_int'),
    path('lista_sintesis/', lista_sintesis, name='lista_sin'),
    path('editar_usuario/', login_required(editar_usuario), name='editar_usuario'),
    path('comentarios/<id>', login_required(comentarios), name='comentarios' ),
    path('registros/', login_required(lista_registros), name='registros' ),
    path('landing_page/', login_required(subir_lan), name='subir_lan'),
    path('act_lan/<id>', login_required(act_lan), name='act_lan'),
    path('dec_lan/<id>', login_required(dec_lan), name='dec_lan'),
    path('subir_documento/', login_required(subir_documento), name='subir_documento'),
    path('act_documento/<id>', login_required(act_documento), name='act_documento'),
    path('des_documento/<id>', login_required(des_documento), name='des_documento'),
    path('elim_documento/<id>', login_required(elim_documento), name='elim_documento'),
    path('borrar_comentario/<doc>/<id>', login_required(borrar_comentario), name='borrar_comentario'),
    path('borrar_comentario/<doc>/<id>', login_required(borrar_comentario), name='borrar_comentario'),
    path('borrar_pdf/<pro>/<id>', login_required(borrar_pdf), name='borrar_pdf'),
    path('pag404/', pag404, name='pag404'),
]

proyecto/models.py
#! / usr / bin / python
# - * - codificación: latin-1 - * -
import os, sys
from django.db import models

#def __unicode__(self):
    #return smart_unicode(("%s" % self.descripcion))

# Create your models here.

class usuario(models.Model):
    usuario = models.CharField(max_length = 20, primary_key = True)
    contraseña = models.CharField(max_length = 30, blank = False, null = False)

class datos_usario(models.Model):
    id_usuario = models.CharField(max_length = 5, primary_key = True)
    usuario = models.CharField(max_length = 20)
    nombre = models.CharField(max_length = 20)
    primer_ap = models.CharField(max_length = 20)
    segundo_ap = models.CharField(max_length = 20)
    telefono = models.CharField(max_length = 10)
    tipo = models.CharField(max_length = 4)

class proyecto(models.Model):
    id_proyecto = models.CharField(max_length = 5, primary_key = True)
    clase = models.CharField(max_length = 40)
    nombre_proyecto = models.CharField(max_length = 50)
    nombre_sin = models.CharField(max_length = 30)
    sintesis = models.TextField()
    porsentaje = models.IntegerField()

class integrantes_proyecto(models.Model):
    id = models.AutoField(primary_key = True)
    id_proyecto = models.CharField(max_length = 5)
    id_usuario = models.CharField(max_length = 5)
    encargo = models.CharField(max_length = 10)

class pdf(models.Model):
    id_pdf = models.AutoField(primary_key = True)
    pdf_nombre = models.CharField(max_length = 50, null = True)
    id_proyecto = models.ForeignKey(proyecto, on_delete = models.CASCADE)
    pdf = models.FileField(upload_to='archivos/archivos/%Y/%m/%d/', default='')
    #fecha = models.DateTimeField(auto_now = True, auto_now_add = False)

class comentario(models.Model):
    id = models.AutoField(primary_key = True)
    id_pdf = models.ForeignKey(pdf, on_delete = models.CASCADE)
    id_usuario = models.ForeignKey(datos_usario, on_delete = models.CASCADE, default='')
    text_comentario = models.TextField()
    #fecha = models.DateTimeField(auto_now = True)

class notificacion(models.Model):
    id = models.AutoField(primary_key = True)
    id_usuario = models.ForeignKey(datos_usario, on_delete = models.CASCADE, default='')
    id_proyecto = models.ForeignKey(proyecto, on_delete = models.CASCADE)
    notificacion = models.CharField(max_length = 150)

class registro(models.Model):
    id = models.AutoField(primary_key = True)
    registro = models.CharField(max_length = 150)

class lan_page(models.Model):
    titulo = models.CharField(max_length = 100)
    imagen = models.ImageField(upload_to='archivos/lan_page/%Y/%m/%d', null=True)
    descripcion = models.TextField(default='')
    link = models.TextField(default='')
    visible = models.CharField(max_length = 1)

class documentos(models.Model):
    documento = models.FileField(upload_to='archivos/documentos/%Y/%m/%d/')
    documento_nombre = models.CharField(max_length = 50, null = True)
    clase = models.CharField(max_length = 40)
    visible = models.CharField(max_length = 1)

proyecto/views.py
#! / usr / bin / python
# - * - codificación: latin-1 - * -
import os, sys
from django.shortcuts import render, redirect
from django.views.generic.edit import FormView
from django.contrib import messages
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.http import HttpResponseRedirect
from django.contrib.auth import login, logout
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.db.models import Q
from .forms import SesionForm
from .forms import ProyectoForm
from .forms import UsuarioForm
from .forms import CuentaForm
from .forms import PdfForm
from .forms import MiembroFrom
from .forms import RegistroFrom
from .forms import ComentarioFrom
from .forms import lan_pageFrom
from .forms import documentosFrom
from .forms import documentosFrom
from .models import proyecto
from .models import integrantes_proyecto
from .models import comentario
from .models import datos_usario
from .models import pdf
from .models import registro
from .models import lan_page
from .models import documentos
from .filters import ProyectosFiltros
from .filters import RegistroFiltros
#from Lab_Investigacion.views import index
import random

from django.utils.encoding import force_bytes

def to_unicode_or_bust(obj, encoding="latin1"):
    if isinstance(obj, basestring):
        if not isinstance(obj, unicode):
            obj=unicode(obj, encoding)
    return obj

# variables intancia

adminA = 'A'
adminD = 'D'

# Create your views here.

def pag404(request):
    return render(request, 'error404.html')

def inicio(request):
    if request.user.is_authenticated:
        return lista_proyectos(request)

    lan = lan_page.objects.filter(visible = '1')

    return render(request, 'inicio.html', {'landing':lan,'activo':'1'})

def ejemplo(request):
    return render(request, 'ejemplo.html')

# crear proyecto ------------------------------------------------------------------------------------------------------------

def crear_proyecto(request):

    if not datos_usario.objects.filter(usuario=str(request.user)):
        return crear_usuario_oficial(request)

    tipo = 0
    usuarios = datos_usario.objects.get(usuario=str(request.user))

    if adminA == usuarios.id_usuario[0]:
        tipo = 1

    if request.method == 'POST':
        proyecto_form = ProyectoForm(request.POST)
        print(proyecto_form)
        if proyecto_form.is_valid():
            num =""

            post = proyecto_form.save(commit=False)

            comprobarcion = True

            while comprobarcion:
                num = generar_numero('P')
                post.id_proyecto = num

                if proyecto.objects.filter(id_proyecto = num):
                    comprobarcion = True
                else:
                    comprobarcion = False

            post.save()

            usuarios = datos_usario.objects.get(usuario=str(request.user))

            if adminA == usuarios.id_usuario[0]:
                tipo = 1

            en = ""

            if usuarios.id_usuario[0] == 'E':
                en = "Integrante"
            else:
                en = "Asesor"

            us = usuarios.id_usuario

            integrantes = integrantes_proyecto(id_proyecto = num, id_usuario = us , encargo = en)

            integrantes.save()

            generar_registro(request, 'creo proyecto ' + num, 0)
            return HttpResponseRedirect('/Lab/integrantes/'+post.id_proyecto)

    else:
        proyecto_form = ProyectoForm()

    return render(request, 'crear_proyecto.html',{'proyectos':'ID','acto':'Crear Proyecto','id':'ID','admin':tipo})

# crear cuenta ---------------------------------------------------------------------------------------------------------------

def crear_cuenta(request):

    usuarios = datos_usario.objects.get(usuario=str(request.user))

    if adminA != usuarios.id_usuario[0]:
        return pag404(request)

    if request.method == 'POST':
        post_usuario = UsuarioForm(request.POST)

        if post_usuario.is_valid():

            num = ""

            post_u = post_usuario.save(commit=False)

            comprobar = True

            while comprobar:

                if post_u.tipo == '1':
                    num = generar_numero('E')

                if post_u.tipo == '2':
                    num = generar_numero('D')

                if post_u.tipo == '3':
                    num = generar_numero('A')

                if datos_usario.objects.filter(id_usuario = num):
                    comprobar = True
                else:
                    comprobar = False

            cuenta = User.objects.create(username=num)

            cuenta.set_password('1234')

            cuenta.save()
            generar_registro(request, 'creo cuenta temporal ' + num, 0)
            messages.info(request, 'Nueva Cuenta: ' + num)

            return redirect('proyecto:crear_cuenta')

    else:
        cuenta_form = UsuarioForm()

    return render(request, 'crear_usuario.html')

# crear usuario-----------------------------------------------------------------------------------------------------------------

def crear_usuario_oficial(request):

    usuario = str(request.user)

    tipo =""

    if usuario[0] == 'D':
        tipo='0'
    else:
        tipo='1'

    if request.method == 'POST':
        usuarios_form = UserCreationForm(request.POST)
        datos_form = UsuarioForm(request.POST)

        if datos_form.is_valid():

            if usuarios_form.is_valid():

                post_datos = datos_form.save(commit=False)
                post_u = usuarios_form.save(commit=False)

                post_datos.usuario = post_u.username
                post_datos.id_usuario = usuario

                post_u.save()
                post_datos.save()
                generar_registro(request, 'fue registrado', 1)

                if usuario != 'marco':
                    u = User.objects.get(username = usuario)
                    u.delete()

                return HttpResponseRedirect('/')
            else:
                messages.info(request, 'Datos Invalidos')
        else:
            messages.info(request, 'Datos Invalidos')
    else:
        usuarios_form = UserCreationForm()
        datos_form = UsuarioForm()

    return render(request,'editar_usuario.html',{'usuario':usuario, 'cero':0, 'tipo':tipo, 'form':usuarios_form})

# subur landing page ------------------------------------------------------------------------------------------------------------------------

def subir_lan(request):

    usuarios = datos_usario.objects.get(usuario=str(request.user))
    if adminA != usuarios.id_usuario[0]:
        return pag404(request)

    land_V = lan_page.objects.filter(visible = '1')
    land_N = lan_page.objects.filter(visible = '0')
    mensaje = ''

    if request.POST:
        landing = lan_pageFrom(request.POST, request.FILES)
        landing.titulo = request.POST.get('titulo')
        landing.imagen = request.FILES.get('imagen')
        landing.descripcion = request.POST.get('descripcion')
        landing.link = request.POST.get('link')
        landing.visible = request.POST.get('visible')

        if landing.is_valid():
            landing.save()
        else:
          mensaje = 'Datos Invalidos'

    else:
        landing = lan_pageFrom()
        print(landing)

    return render(request, 'lan_page.html', {'lan_V':land_V, 'land_N':land_N, 'mensaje':mensaje})

def act_lan(request, id):

    usuarios = datos_usario.objects.get(usuario=str(request.user))
    if adminA != usuarios.id_usuario[0]:
        return pag404(request)

    anuncio = lan_page.objects.get(id = id)
    anuncio.visible = '1'

    anuncio.save()

    return subir_lan(request)

def dec_lan(request, id):

    usuarios = str(request.user)
    if adminA != usuarios.id_usuario[0]:
        return pag404(request)

    anuncio = lan_page.objects.get(id = id)
    anuncio.visible = '0'

    anuncio.save()

    return subir_lan(request)

# subur documento ------------------------------------------------------------------------------------------------------------------------

def subir_documento(request):

    usario = datos_usario

    try:
        usuarios = datos_usario.objects.get(usuario = str(request.user))
    except Exception as e:
        return pag404(request)

    if adminA != usuarios.id_usuario[0]:
        return pag404(request)

    consulta = documentos.objects.all()

    if request.POST:
        doc = documentosFrom(request.POST, request.FILES)
        doc.documento_nombre = request.POST.get('documento_nombre')
        doc.clase = request.POST.get('clase')
        doc.documento = request.POST.get('documento')
        doc.visible = request.POST.get('visible')

        if doc.is_valid():
            doc.save()
        else:
          mensaje = 'Datos Invalidos'

    else:
        doc = documentosFrom()
        #print(doc)

    return render(request, 'documentos.html', {'documento':consulta})

# Activar documento ------------------------------------------------------------------------------------------------------------------------

def act_documento(request, id):

    usario = datos_usario

    try:
        usuarios = datos_usario.objects.get(usuario = request.user)
    except Exception as e:
        return pag404(request)

    if adminA != usuarios.id_usuario[0]:
        return pag404(request)

    doc = documentos.objects.get(id = id)
    doc.visible = '1'
    doc.save()

    return subir_documento(request)

# Des documento ------------------------------------------------------------------------------------------------------------------------

def des_documento(request, id):

    usario = datos_usario

    try:
        usuarios = datos_usario.objects.get(usuario = request.user)
    except Exception as e:

templates/comentarios.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <link rel="icon" type="image/png" href="{% static 'img/icons/logotec.ico' %}"/>
    <title>Comentario</title>
  </head>
  <body>

    {% if 1 == admin %}
      {% include "menu/menu_admin.html" %}
    {% else %}
      {% include "menu/menu_interno.html" %}
    {% endif %}

    <div class="row d-flex justify-content-center mt-5 wrapper contenido ">

      <div class="container col-sm-9">
        {% if comentarios %}
          {% for comentario in comentarios %}
            {% for usuario in usuarios %}
              {% if usuario.id_usuario == comentario.id_usuario.id_usuario %}
                {%if us.id_usuario == comentario.id_usuario.id_usuario%}
                  <div class="card">
                    <div class="card-body">
                      <h3 text-right>{{usuario.nombre}} <a data-toggle="modal" href="" data-target="#exampleModalCenter{{comentario.id}}">X</a> </h3>
                      <div class="card">
                        <p class="mr-3 ml-3">{{comentario.text_comentario}}</p>
                      </div>
                    </div>
                  </div>
                  <div class="modal fade" id="exampleModalCenter{{comentario.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle{{comentario.id}}" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h5 class="modal-title" id="exampleModalLongTitle{{comentario.id}}">Borrar Comentario</h5>
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                          <a type="button" class="btn btn-primary" href="{% url 'proyecto:borrar_comentario' comentario.id_pdf.id_pdf comentario.id %}" >Borrar</a>
                        </div>
                      </div>
                    </div>
                  </div>
                {%else%}
                  <div class="card">
                    <div class="card-body">
                      <h3>{{usuario.nombre}}</h3>
                      <div class="card">
                        <p class="mr-3 ml-3">{{comentario.text_comentario}}</p>
                      </div>
                    </div>
                  </div>
                {%endif%}
              {% endif %}
            {% endfor %}
          {% endfor %}
        {% else %}
          <div class="card ">
            <div class="card-body">
              <h1 class="card-title text-center">No hay comentarios</h1>
            </div>
          </div>
        {% endif %}

        <div class="card mt-4">
          <h3 class="card-header" >Nuevo Comentario</h3>
          <div class="card-body">
            <form class="" method="post">
              {% csrf_token %}
              <input type="text" name="id_pdf" id="id_id_pdf"  value="{{id}}" style="display:none">
              <label for="id_id_usuario" style="display:none" >Id usuario:</label><input name="id_usuario" id="id_id_usuario" readonly class="form-control" value="{{us.id_usuario}}" style="display:none">
              <textarea name="text_comentario" cols="40" rows="3" required id="id_text_comentario" class="form-control"></textarea>
              <button type="submit" name="button" class="btn float-right btn-primary">Comentar</button>
            </form>
          </div>
        </div>

      </div>

    </div>

  </body>
</html>

templates/crear_proyecto.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <link rel="icon" type="image/png" href="{% static 'img/icons/logotec.ico' %}"/>
    <title>Crear Proyecto</title>
  </head>
  <body>
    {% if 1 == admin %}
      {% include "menu/menu_admin.html" %}
    {% else %}
      {% include "menu/menu_interno.html" %}
    {% endif %}
    <div class="row d-flex justify-content-center wrapper contenido " style="padding-top:100px">
      <div class="card col-md-6">
        <h5 class="card-header">{{acto}}</h5>
        <div class="card-body">
          <form method="post">
            {% csrf_token %}
            <div class="form-group">
              <label for="id_id_proyecto">ID del proyecto</label>
              <input type="text" readonly name="id_proyecto" id="id_id_proyecto" maxlength="5" class="form-control" placeholder="ID AutoGerado" value="{{id}}{{proyectos.id_proyecto}}" >
            </div>
            <div class="form-group">
              <label for="id_clase">Clase:</label>
              <select type="text" name="clase" maxlength="30" required id="id_clase" class="form-control" selected value="{{proyectos.clase}}">
                <option value="Articulo Revista Indexada"
                {%if proyectos.clase == 'Articulo Revista Indexada' %}
                  selected="selected"
                {%endif%}>Articulo Revista Indexada</option>
                <option value="Articulo Revista Indexada JCR"
                {%if proyectos.clase == 'Articulo Revista Indexada JCR' %}
                  selected="selected"
                {%endif%}>Articulo Revista Indexada JCR</option>
                <option value="Patente"
                {%if proyectos.clase == 'Patente' %}
                  selected="selected"
                {%endif%}>Patente</option>
                <option value="Derecho de Autor"
                {%if proyectos.clase == 'Derecho de Autor' %}
                  selected="selected"
                {%endif%}>Derecho de Autor</option>
                <option value="innovación"
                {%if proyectos.clase == 'innovación' %}
                  selected="selected"
                {%endif%}>innovación</option>
                <option value="Proceedings"
                {%if proyectos.clase == 'Proceedings' %}
                  selected="selected"
                {%endif%}>Proceedings</option>
                <option value="Tesis"
                {%if proyectos.clase == 'Tesis' %}
                  selected="selected"
                {%endif%}>Tesis</option>
                <option value="Cerificación"
                {%if proyectos.clase == 'Cerificación' %}
                  selected="selected"
                {%endif%}>Cerificación</option>
              </select>
            </div>
            <div class="form-group">
              <label for="id_nombre_proyecto">Nombre proyecto:</label>
              <input type="text" name="nombre_proyecto" maxlength="50" required id="id_nombre_proyecto" class="form-control" value="{{proyectos.nombre_proyecto}}">
            </div>
            <div class="form-group">
              <label for="id_nombre_sin">Titulo Síntesis:</label>
              <input type="text" name="nombre_sin" maxlength="30" required id="id_nombre_sin" class="form-control" value="{{proyectos.nombre_sin}}">
            </div>
            <div class="form-group">
              <label for="id_sintesis">Síntesis:</label>
              <textarea name="sintesis" cols="50" rows="5" required id="id_sintesis" class="form-control">{{proyectos.sintesis}}</textarea>
            </div>
            <div class="form-group">
              <label for="id_porsentaje">Porsentaje:</label>
              <input type="number" name="porsentaje" required id="id_porsentaje"  class="form-control" value="{{proyectos.porsentaje}}">
            </div>
        <button type="submit" name="" class="btn float-right btn-primary">Crear</button>
      </form>
      <h5 class="text-center">{{ form.non_field_errors }}</h5>
        </div>
      </div>
    </div>
  </body>
</html>

templates/crear_usuario.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    {% load staticfiles %}
    <link rel="icon" type="image/png" href="{% static 'img/icons/logotec.ico' %}"/>
    <title>Nuevo Usuario</title>
  </head>
  <body>

    {% include "menu/menu_admin.html" %}

    <div class="row d-flex justify-content-center wrapper contenido " style="padding-top:100px">
      <div class="col-sm-6">

        <form method="post">
          {% csrf_token %}

          <div class="card">
            <h5 class="card-header">Nuevo Usuario</h5>
            <div class="card-body">

              <div class="form-group">
              <p style="display:none;"><label for="id_id_usuario">Id Usuario:</label> <input type="text" name="id_usuario" maxlength="5" value="0" required id="id_id_usuario"></p>
              <p style="display:none;"><label for="id_usuario">Id Usuario:</label> <input type="text" name="usuario" maxlength="20" value="0" required id="id_usuario"></p>
              <p style="display:none;"><label for="id_nombre">Nombre:</label> <input type="text" name="nombre" maxlength="20" value="0" required id="id_clase"></p>
              <p style="display:none;"><label for="id_nprimer_ap">Primer Apellido:</label> <input type="text" name="primer_ap" value="0" maxlength="50" required id="id_primer_ap"></p>
              <p style="display:none;"><label for="id_segundo_ap">Segundo Apellido:</label> <input type="text" name="segundo_ap" value="0" maxlength="30" required id="id_segundo_ap"></p>
              <p style="display:none;"><label for="id_telefono">Telefono:</label><input name="telefono" cols="40" rows="20" value="0" required id="id_telefono"></p>
              <div class="form-group">
                <label for="id_tipo">Tipo de Usuario:</label> <select name="tipo" class="form-control" required id="id_tipo"><option value="1">Estudiante</option><option value="2">Docente</option><option value="3">Administrador</option></select>
              </div>
              <button type="submit" class="btn btn-primary float-right">Crear</button>
              </div>

            </div>
          </div>
        </form>
      </div>

      {% if messages %}
          {% for message in messages %}
              <div class="card">
                <h5 class="card-header">Nuevo Usuario</h5>
                <div class="card-body">
                  <h4>{{message}}</h4>
                  <h4>Conraseña: 1234</h4>
                </div>
              </div>
          {% endfor %}
      {% endif %}

    </div>
  </body>
</html>

templates/editar_usuario.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <link rel="icon" type="image/png" href="{% static 'img/icons/logotec.ico' %}"/>
    {% if 0 == cero %}
      <title>Nuevo Usuario</title>
    {% else %}
      <title>Editar Usuario</title>
    {% endif %}

    <script type="text/javascript" href="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script type="text/javascript" href="{% static 'js/ContraseñaScript.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

  </head>
  <body>

    {% if 1 == admin %}
      {% include "menu/menu_admin.html" %}
    {% else %}
      {% include "menu/menu_interno.html" %}
    {% endif %}

    <div class="row d-flex justify-content-center wrapper contenido " style="padding-top:50px">

          <div class="card  col-md-6">
            <h1 class="card-header">Usuario</h1>
            <div class="card-body">
              <form class="" method="post">
                {% csrf_token %}
                <div class="card-title">
                  <h5>ID: {{id}}</h5>
                </div>

                  <div class="form-group">
                    <input type="text" name="username" id="id_username" placeholder="Usuario" class="form-control" value="{{cuenta.usuario}}{{datos.usuario}}">
                  </div>

                  <div class="form-group">
                    <p>La contraseña debe tener al menos 8 caracteres con letras y números, comienza con una letra</p>
                    <input type="password" name="password1" id="id_password1" class="form-control" placeholder="Contraseña"/>
                  </div>

                  <div class="form-group">
                    <input type="password" name="password2" id="id_password2" class="form-control" placeholder="Volver Introducir la Contraseña"/>
                  </div>

                  <div class="form-group">
                    {% if 0 == cero %}
                    <p style="display:none;"><label></label><input type="text" name="id_usuario" id="id_id_usuario" value="{{datos.id_usuario}}{{cero}}"></p>
                    <p style="display:none;"><label></label><input type="text" name="usuario" id="id_usuario" value="{{datos.usuario}}{{cero}}"></p>
                    {% else %}
                    <p style="display:none;"><label></label><input type="text" name="id_usuario" id="id_id_usuario" value="{{datos.id_usuario}}"></p>
                    <p style="display:none;"><label></label><input type="text" name="usuario" id="id_usuario" value="{{datos.usuario}}"></p>
                    {% endif %}

                  </div>

                  <div class="form-group">
                    <input type="text" name="nombre" id="id_nombre"  class="form-control" placeholder="Nombre" value="{{datos.nombre}}">
                  </div>

                  <div class="form-group">
                    <input type="text" name="primer_ap" id="id_primer_ap"  class="form-control" placeholder="Apellido Paterno" value="{{datos.primer_ap}}">
                  </div>

                  <div class="form-group">
                    <input type="text" name="segundo_ap" id="id_segundo_ap"  class="form-control" placeholder="Apellido Materno" value="{{datos.segundo_ap}}">
                  </div>

                  <div class="form-group">
                    <input type="text" name="telefono" id="id_telefono"  class="form-control" placeholder="Telefono" value="{{datos.telefono}}">
                  </div>

                  <p style="display:none;"><label></label><input type="text" name="tipo" id="id_tipo" value="{{datos.tipo}}{{tipo}}"></p>

                  {% if 0 == cero %}
                    <button type="submit" name="button" class="btn float-right btn-primary ">Crear usuario</button>
                  {% else %}
                    <button type="submit" name="button" class="btn float-right btn-primary ">Actializar</button>
                  {% endif %}

              </form>
            </div>
            {% if messages %}
                {% for message in messages %}
                  <h5>{{message}}</h5>
                {% endfor %}
            {% endif %}
          </div>

      <h4 class="text-center">{{ form.non_field_errors }}</h4>

    </div>

  </body>

</html>